### ISSUE TITLE
first taxonomic treatment in BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#102]
Just a throught, now that we have the taxonomic treatment in place.

> Hi Donat & Guido,
> Everything is deployed and good to go in both systems now. We've added the "openbiodiv:TaxonomicConceptLabel" custom keyword as well.
> Guido, feel free to shoot things at any of the systems, and let me know if you come across any unexpected errors.
> Cheers,
> Alex
> 

Why don't we think for a moment which should be the first treatment we upload before Guido starts with the upload?

it should be one that we can use to demonstrate various aspects of what we intend to do, such as  adding all the links in the metadata, the kind of custom metatdata, the link to GBIf and from GBIF,

Any ideas?

**Comment by gsautter** [comment]
How about the big one we've been using in the sandbox tests? It contains all the kinds of citations/links we have, and several instances of each: http://tb.plazi.org/GgServer/html/03C88554FF8FFFB2FF53F9E86AD50709

**Comment by gsautter** [comment]
Or re we rather looking for a specific species, or species from a specific genus or family?

**Comment by myrmoteras** [comment]
not a Zootaxa!

I guess best would be a EJT including a treatment with a new species, one with a treatment citation, and with a link to a specimen / DNA accession number both with links. Ideally it would be one, where we have the cited treatment as well, so that we at some point could add the link too. If you are aware of one, then lets use it.

**Comment by gsautter** [comment]
OK, I'll try and dig something up from the stats.

**Comment by gsautter** [comment]
Profundiconus virginiae (European Journal of Taxonomy 173), original description with links on several figure and materials citations: http://tb.plazi.org/GgServer/html/24768796CD18FFCBFDF716FEFD45FAD9

I cannot seem to find an EJT treatment with a linked treatment citation ... any other preferences?

**Comment by myrmoteras** [comment]
this is a good one. I am adding the specimen code as well. I hope, this is still ok httpUri-0, httpUri-1

**Comment by gsautter** [comment]
The numbered HTTP URIs are definitely good, just make sure to start with 0 and not omit an intermediate number. If there is only one HTTP URI, omit the numbering altogether, i.e., `httpUri` instead of `httpUri-0`.

**Comment by myrmoteras** [comment]
when you look at the one above, it has in this holotype both a linked specimenCode as well as a Accession code. but the linking works diffrently:

`<materialsCitation collectionCode="MNHN" collectorName="V Alis" country="Solomon Islands" elevation="421" httpUri="http://coldb.mnhn.fr/catalognumber/mnhn/im/2007-34878" latitude="-9.316667" location="R / V Alis, SALOMONBOA 3 Expedition, st. CP 2767" longLatPrecision="1300" longitude="160.1" pageId="18" pageNumber="19" specimenCode="IM-2007-34878" specimenCount="1" stateProvince="Guadalcanal" typeStatus="holotype">
<collectingCountry box="[189,476,698,724]" name="Solomon Islands" pageId="18" pageNumber="19">SOLOMON ISLANDS</collectingCountry>
: 27.5 ×
<quantity box="[588,702,697,724]" metricMagnitude="-2" metricUnit="m" metricValue="1.26" pageId="18" pageNumber="19" unit="mm" value="12.6">12.6 mm</quantity>
,
<location LSID="urn:lsid:plazi:treatment:24768796CD1FFFC6FDED1609FD27FE12:A900605BCD1FFFC1FD6D15B8FA8AFD14" box="[719,1394,697,724]" country="Solomon Islands" latitude="-9.316667" longLatPrecision="1300" longitude="160.1" name="R / V Alis, SALOMONBOA 3 Expedition, st. CP 2767" pageId="18" pageNumber="19" stateProvince="Guadalcanal">
R/V
<emphasis box="[781,827,697,723]" italics="true" pageId="18" pageNumber="19">Alis</emphasis>
, SALOMONBOA 3 Expedition, st. CP 2767
</location>
,
<collectingRegion box="[189,339,733,759]" country="Solomon Islands" name="Guadalcanal" pageId="18" pageNumber="19">Guadalcanal</collectingRegion>
,
<geoCoordinate box="[354,445,733,759]" direction="south" orientation="latitude" pageId="18" pageNumber="19" precision="925" value="-9.316667">9°19' S</geoCoordinate>
,
<geoCoordinate box="[462,569,733,759]" direction="east" orientation="longitude" pageId="18" pageNumber="19" precision="925" value="160.1">160°6' E</geoCoordinate>
,
<quantity box="[585,722,732,759]" metricMagnitude="2" metricUnit="m" metricValue="4.205" metricValueMax="4.25" metricValueMin="4.16" pageId="18" pageNumber="19" unit="m" value="420.5" valueMax="425.0" valueMin="416.0">
<elevation box="[585,722,732,759]" metricMagnitude="2" metricUnit="m" metricValue="4.205" metricValueMax="4.25" metricValueMin="4.16" pageId="18" pageNumber="19" unit="m" value="420.5" valueMax="425.0" valueMin="416.0">416–425 m</elevation>
</quantity>
(
<collectionCode box="[741,833,733,759]" collectionName="France, Paris, Museum National d'Histoire Naturelle" country="France" httpUri="http://biocol.org/urn:lsid:biocol.org:col:34988" name="Museum National d'Histoire Naturelle" pageId="18" pageNumber="19">MNHN</collectionCode>
<specimenCode box="[844,1035,733,759]" collectionCode="IM-" pageId="18" pageNumber="19">IM-2007-34878</specimenCode>
;
<figureCitation box="[1051,1148,733,759]" captionStart="Fig. 7" captionStartId="19.[189,232,1896,1922]" captionTargetBox="[249,1339,265,1868]" captionTargetId="figure@19.[249,1339,265,1868]" captionTargetPageId="19" captionText="Fig. 7. Profundiconus maribelaesp. nov.A. Holotype, 27.5 × 12.6 mm.B. Paratype1, 30.0 ×12.5 mm. C. Paratype 2, 30.4 × 13.1 mm. D. Paratype 2, enlargement of the spire. E. Paratype 3 (broken shell), 27.2 × 12.4 mm. F. Sequenced specimen (MNHN IM-2007-34879), 31.5 × 14.4 mm. G. Radular tooth from paratype 1. Scale bars = 10 mm unless otherwise indicated." httpUri="https://zenodo.org/record/1182507/files/figure.png" pageId="18" pageNumber="19">Fig. 7A</figureCitation>
; GenBank accession number (
<emphasis box="[296,351,768,794]" italics="true" pageId="18" pageNumber="19">cox1</emphasis>
sequence):
<accessionNumber box="[491,618,768,795]" httpUri="http://www.ncbi.nlm.nih.gov/nucleotide/KJ550452" pageId="18" pageNumber="19">KJ550452</accessionNumber>
).
</materialsCitation>
`

**Comment by gsautter** [comment]
Hard one ... this is just one instance of a more general problem: where to put the multitude of potential outgoing links in an MC? We don't have general policy for this thus far, and the stats (along with the TB website) cover only links on the `materialsCitation` proper at the moment. The latter is rather easy to change, however.
A general policy might be to put links as closely as possible to the plain text part representing them:
- like the link on the accession number, it's right where it belongs.
- in that regard, digital specimen links should go on any present `specimenCode` annotations if available (using the numbering mechanism on specimen code ranges), and on the `materialsCitation` proper only if no specimen codes are annotated.
- the same applies to GenBank numbers
- are there any other linkable details in MCs?

Suggestions, please ... or opinions, additions, corrections, whatever.

**Comment by myrmoteras** [comment]
if this is possible to add the httpUri/doi to the tagged element as you state this above, that's the best I can imagine.

We need also to think in the longer term and further downstream.
How does this translate into Taxpub?
How does this translate into the GG XML we add to the Treatment deposit?
How does this translate into the DWCA that we serve GBIF and potential further clients?
How does this translate into the treatment Deposit metadata '- eventually this should be  a dwc custom element "Genaccession link", "specimen code link", "BOLDAcession link"

**Comment by gsautter** [comment]
Regarding TaxPub, maybe the way the Pensoft guys represent the UUIDs might be a way to go.

The GG XML added to the deposit has a blacklist based filter, so any newly added elements will go through at first ... it is basically the same XML as we use throughout the respective stages of the server with a few obsolete elements and attributes stripped out.

In DwC-A, we likely have to work on a case-by-case basis, depending on the availability of corresponding DwC terms.

In depositions, we might simply augment and use the upcoming typing system for related identifiers.

All of these points should be separate tickets, however. Let's get this one back on focus, please.

**Comment by gsautter** [comment]
One more on the general problem, though: While _representing_ all these links in our various export formats is an important aspect, I tend to think the even more important one is how we can automatically _create_ or _import_ these links, be it as part of the batch or via a dedicated function in some menu in GGI. Without the latter, we will just end up with a multitude of fields that are empty in 99.9% of our data.

**Comment by myrmoteras** [comment]
if there is no content, then just don't use the field?!

**Comment by gsautter** [comment]
While this is very much possible in annotation attributes inside documents proper, as well as Zenodo depositions, it is way harder a thing to do in DwC-As, and outright impossible in the stats (in a database table, a column always exists in all records, which is a fundamental principle of relational databases).

**Comment by gsautter** [comment]
And in more general terms, what good is supporting a property or field throughout our infrastructure if it is empty in 99.9% of the cases?

**Comment by gsautter** [comment]
Not saying we have to implement all the automation right away, just wanting to say that for the whole effort to really make sense beyond a few demo cases, it's something we need to consider.

And now back to the original focus of this ticket, please.

**Comment by gsautter** [comment]
I did a live fire test, and it's looking good ... what do you think? See https://zenodo.org/record/3472000

**Comment by gsautter** [comment]
No worries, the automated export on all treatment updates is still deactivated. It's manual firing only at this point, but from the live system.

**Comment by myrmoteras** [comment]
@gsautter can you pleas upload this one?
2A6BF5710C5EFFAFDA74DF66FFA31E0D - its one for which we have valid taxpub
