### ISSUE TITLE
BRL items owenership

### ISSUE THREAD

**Issue by teodorgeorgiev** [plazi/arcadia-project#107]
Hi @slint,

There are still issues with the ownership of the items submitted from us to BRL repo.

Could you please transfer all items submitted from "preprint" account and currently assigned to BLR-repo under "plazi-admin" account, so I can find, edit & publish them using only PLAZI_ACCOUNT_TOKKEN.

For example depositon 574370 (https://zenodo.org/deposit/574370), which is BLR, is accessible only with PENSOFT_ACCOUNT_TOKKEN, but not with PLAZI_ACCOUNT_TOKKEN. 

Could please let me know as soon as this is done? Thanks in advance!

**Comment by slint** [comment]
I think back when we did the original transfer, you gave us a list of deposit IDs, and we went through them to transfer only specific records. For example, the "preprint" account has 22.420 records at the moment: https://zenodo.org/search?q=owners:22270

Should I transfer all of these to the "plazi-admin" account?

**Comment by teodorgeorgiev** [comment]
Hi Alex, please transfer only the following 16035 to the "plazi-admin" account:
https://zenodo.org/search?page=1&size=20&q=(owners:22270%20AND%20communities:%20biosyslit)

The rest 8385 should stay under "preprint" account.

**Comment by teodorgeorgiev** [comment]
Hi @slint, sorry for pushing for this issue, but it is a kind of urgent. 
Guido waiting for me to add zenodo deposition IDs in TaxPub Xml, which I can not do before the transfer of these items. We want to have our content proceesed also before Lieden. 
Is it possible for you to do this today?

**Comment by slint** [comment]
I've kicked-off a script to do the transfer, it seems to be transferring ~100records/min, so It will be finished in roughly 3hours. I'll post a comment here when it finishes

**Comment by teodorgeorgiev** [comment]
10x Alex, much appreciated!

**Comment by slint** [comment]
Apparently it started being much slower as the day went by (could be extra traffic, etc). It's currently half way there (8k/16k), but I'll leave it running. You can always check the progress by visiting the search link

**Comment by teodorgeorgiev** [comment]
It is done, thanks Alex!
