### ISSUE TITLE
taxonomic treatment @ BLR: upload of botanial articles

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#114]
@gsautter can you please upload a couple of treatments for  botanical articles to BLR:

323E7E30FFDEE562CF26FFBE1C53B21B 
FFA3242A7B320731FFA8FFE8981AFFA5
974EFD592A52FFDF2A5FC529FF8CFF8F
FF9FCE0DFFF8FFF50066D663FFB7B660
FFDFFFF57E64107E9F2AFFD53965FFCA
FFE4FFA0FFF5D207FFE0A659703AFFCC
FFFF4903FFA6FFCBFF82E940FFBAFFE6

**Comment by gsautter** [comment]
Uploaded, just had to fix some minor table annotation issues in one single treatment.
