### ISSUE TITLE
T.Rex treatmentCitation in BLR: where do we stand?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#119]
@gsautter 
what are the plans with treatmentCitation upload to BLR? 
This is a nice example with many TC that have links to treatments in TB http://tb.plazi.org/GgServer/html/03858796EA19FF998DEAFE40FBBBF8E6 

![image](https://user-images.githubusercontent.com/4609956/67041943-0caa0b80-f127-11e9-9185-2d80963a16d2.png)

this is the DOI https://doi.org/10.5281/zenodo.3482998

these are the treatmentCitation in the BLR deposit

![image](https://user-images.githubusercontent.com/4609956/67042073-5e529600-f127-11e9-995b-fa910256aaea.png)
Will they become DOIs too? There is only one, but it is a broken link 
![image](https://user-images.githubusercontent.com/4609956/67042141-8d690780-f127-11e9-877a-32264cc55913.png)

**Comment by gsautter** [comment]
Looks like the cited treatment didn't go on Zenodo just yet ... I'll take care of it soon as the treatments for https://github.com/plazi/arcadia-project/issues/118 are through.

**Comment by gsautter** [comment]
Fixed. Will automatically update now as the cited treatments go to Zenodo. I've escalated the treatment uploader from having to manually trigger each and every upload to automatically _updating_ existing depositions, but creating new ones only if triggered manually.
