### ISSUE TITLE
next Arcadia sprint 2020, February 24-28, 2020

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#130]
here the link to the GGD to collect notes in preparation of the meeting https://docs.google.com/document/d/1K9O3qaaqMZQfEQY06k_Qpr0rbPsEu32vbPwD1KRcRjA/edit#

@slint @lnielsen @punkish @tcatapano @teodorgeorgiev @mguidoti @ChiaraBi 

Following our framadate https://framadate.org/arcadia and consulting our agendas, the week of Feb 24-28 seems to be the only time to suit most of us. Unfortunately, Marcus will not join us, unless he can change the date, but Guido and I will travel to meet Marcus and run together a workshop in Brazil the coming week and visit our new POA office in Port Alegre, which will give us time to debrief him. At the same time we can skype him in, and go through the documentation he and the team is preparing and fill in technical parts.

If you agree, then lets decide and get out flights, and may be a place at the CERN hotel within CERN this time. Possible @slint @lnielsen ?

Please reply asap

**Comment by slint** [comment]
I'll check-in with Jose to see what's the procedure and reply here. How many people will there be in total? From the framadate (and some assumptions) I guess it's, Guido, Donat, Terry, Johannes, Teodor, Puneet, so **6 in total**.

**Comment by myrmoteras** [comment]
in this realm

**Comment by myrmoteras** [comment]
@slint we will stay not at the CERN Hotel, but our old venue, but rent a car. we then need a pass to enter CERN

**Comment by myrmoteras** [comment]
@slint I assume that the  dates are confirmed, so we can proceed buying tickets?!

**Comment by slint** [comment]
Yes, go ahead, we'll start organizing the access requests and logistics at CERN as well

**Comment by myrmoteras** [comment]
@gsautter @tcatapano @teodorgeorgiev Please let me know by **tomorrow Dec 12** how many nights you want to stay during the next Sprint.
We will book again the the IBIS, but this time we'll rent a car so we are more flexible and can cut down on walking time.

**Comment by gsautter** [comment]
I think arriving on 23rd and staying through 28th makes the most sense for me, so that's 5 nights Sun-Fri.

**Comment by teodorgeorgiev** [comment]
arriving on Monday (24th), leaving on Friday (28th), so 4 nights

**Comment by tcatapano** [comment]
5 nights, 23rd to 28th.

**Comment by mguidoti** [comment]
> Yes, go ahead, we'll start organizing the access requests and logistics at CERN as well

@slint, could you please include me in these access requests? 

Thanks

**Comment by myrmoteras** [comment]
The hotel IBIS Budget St Genis is booked
Feb 23-28 for @myrmoteras @gsautter @tcatapano @mguidoti @punkish 
Feb 24-28 for @teodorgeorgiev

**Comment by gsautter** [comment]
Please don't forget Johannes ... he would love to join the sprint as well, told be so multiple times.

**Comment by gsautter** [comment]
Johannes would want to join us all week, so his dates are the same as mine, Feb 23-28.

**Comment by myrmoteras** [comment]
Dear Donat,
I confirm we will present the SONAR project on Feb 27. I will make sure we present the SIBiLS services, which store the BioC-formated data. I will also inform Miguel Moreira from RERO, who might be willing to join.
I personnally must be in Luxembourg that day (27-28) for the final review of the MyHealthMyData project.
Best wishes,
Patrick

**Comment by myrmoteras** [comment]
add a **wild ideas** section in program

**Comment by myrmoteras** [comment]
peter Cornwell an additional participant for a day or so

**Comment by myrmoteras** [comment]
@slint @lnielsen @punkish @tcatapano @teodorgeorgiev @mguidoti @ChiaraBi araBi @gsautter @retog

reminder:
there is less than one week to go to our next Sprint. Please go throug the google doc and write down YOU wishes to be discussed. 
Also, we will have Peter Cornwell to discuss Person Names, and Julien Gobeil to present SIBs work on Text and Data Mining 

Please add your ideas to https://docs.google.com/document/d/1K9O3qaaqMZQfEQY06k_Qpr0rbPsEu32vbPwD1KRcRjA/edit#

**Comment by myrmoteras** [comment]
Dear Donat,

> I assume you will come on Thursday?!

Yes I will. Yet, I have teaching on the morning, thus won't be able to leave Carouge until 12:30. Moreover, the agenda - and closing time - will also determine whether I come with my car or by public transport.

Best,

J
Gobeill Julien (HES) <julien.gobeill@hesge.ch>

**Comment by myrmoteras** [comment]
Lieber Donat

Ja, ich kann am Dienstag nach Genf fahren und am Donnerstag oder Freitag zurückfahren.

Liebe Grüsse
Reto

**Comment by myrmoteras** [comment]
Dear all,
In preparation of the upcoming Arcadia Sprint taking place during the 24-28th February at CERN, I kindly request all of you to register for the event, by Monday 24th 8:00AM, at the following link:
https://indico.cern.ch/event/871542/
Registration is mandatory in order to access the CERN campus!
Regarding access to the campus by car, you'll need to fill-in the car's license plate during the registration, so @Donat you'll have to wait until you get the car on Sunday night to register.
From previous discussions/emails, I've come up with the following participant list: 
•	Donat Agosti (agosti@amnh.org)
•	Terry Catapano (catapanoth@gmail.com)
•	Peter Cornwell (peterc@data-futures.org)
•	Teodor Georgiev (teodor.pensoft@gmail.com)
•	Marcus Guidoti (marcus.guidoti@gmail.com)
•	Johannes Hamann (johannes.hamann@clouz.de)
•	Puneet Kishor (punk.kish@gmail.com)
•	Patrick Ruch (patrick.ruch@hesge.ch)
•	Guido Sautter (gsautter@googlemail.com)
Please review the list to see if I've forgotten someone, or let me know if you're aware of others that are joining.
I'm very excited and looking forward to see you all again here at CERN
Cheers,
Alex

**Comment by myrmoteras** [comment]
@slint 
Please also enter the two additional persons:
Gobeill Julien (HES) julien.gobeill@hesge.ch Who will replace Patrick Ruch
Reto Gmür Reto Gmür reto@factsmission.com
Peter Cornwell peter cornwell <peterc@data-futures.org >

**Comment by retog** [comment]
I just tried to register but it says: 

    There is already a registration with this email address.

However I haven't got an email with the access pass.

**Comment by slint** [comment]
@retog, and everybody else except @myrmoteras (because of the car, as we discussed you'll get receive it on Sunday evening), I just send out the emails which have a PDF attachment with your access badge and also a code you can use at CERN's reception in case you want to print the access badge when you arrive.
