### ISSUE TITLE
processing: The head anatomy of Protanilla lini (Hymenoptera: Formicidae: Lep

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#169]
can you please process this article:

https://myrmecologicalnews.org/cms/index.php?option=com_download&view=download&filename=volume31/mn31_85-114_printable.pdf&format=raw

not urgent (within a week)
Level: subsection, upload to BLR

**Comment by valdenar** [comment]
Hi Donat,
The individual extraction has been completed. 
Follow UUID: FFEFFFBBFFF2FFCFFFF4FFC1FFA71A65
