### ISSUE TITLE
Meeting: 20190315-16 Sofia: logistics

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#21]
Set up the logistics for the meeting in Sofia:
Agenda
Hotel

**Comment by teodorgeorgiev** [comment]
@myrmoteras  Please try to book the hotel at Silver house hotel, or other (I don't know if there are any hotel suggestions for MOBILISE kick-off):

https://www.booking.com/hotel/bg/silver-house.en-gb.html?aid=311984;label=hotel-bg-29351-en-5sboICQwM3UeVcEhJCG%2AvAS152094094200%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap1t1%3Aneg%3Afi%3Atiaud-285284111486%3Akwd-11140381877%3Alp1001448%3Ali%3Adec%3Adm;sid=8a4090d85cc049b5f05602718f63f8f4;dest_id=-838489;dest_type=city;dist=0;hapos=1;hpos=1;room1=A%2CA;sb_price_type=total;srepoch=1550222875;srfid=55848e95ce58fa47e57c018bb849ce9a78aa0218X1;srpvid=7d20428de21e02fb;type=total;ucfs=1&#hotelTmpl

Agenda:
https://github.com/plazi/Plazi-Communications/wiki/Plazi-Pensoft-Arcadia-workshop-@-Sofia

**Comment by myrmoteras** [comment]
for mobilise we are in the academy hotel

**Comment by teodorgeorgiev** [comment]
okey, you can stay there if you want and I will pick up you from the academy hotel
