### ISSUE TITLE
sprint 3: CERN access

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#229]
@lnielsen @slint here is the link to the participants for the sprint.

https://docs.google.com/spreadsheets/d/1juEXsItKQBdN23vpim86NjM9ZuvhP_e7UH9j9qhXxek/edit#gid=0

can you please organize the permits to enter the CERN facility?

**Comment by myrmoteras** [comment]
Hi Lars and Alex
Can you please make sure that everybody is registered at CERN and then can fill in the respective details BEFORE the meeting? https://github.com/plazi/arcadia-project/issues/229

Thanks
Donat

**Comment by slint** [comment]
Hi Donat,

Sorry for the late reply. For access to CERN for next week's sprint everyone has to register at https://indico.cern.ch/event/1339594/registrations/99194/

Ideally before Sunday 29/10, since we'll have to accept the requests on our side.

**Comment by slint** [comment]
Forgot to mention, the meeting room is at the ground floor of the Zenodo office building, so no trekking gear or map required this time to reach it, and hopefully there's no fire alarm drill this time :)

**Comment by flsimoes** [comment]
Registered (feel free to add your names to the list):
- Felipe

**Comment by gsautter** [comment]
registered

**Comment by flsimoes** [comment]
Not sure when we'll get the badges to print, but so far we haven't got anything

**Comment by slint** [comment]
I've just confirmed your registrations and sent out the badges/tickets via email.

**Comment by flsimoes** [comment]
Thanks Alex! Just received it.

**Comment by stgrub** [comment]
Stephanie: registered yesterday
