### ISSUE TITLE
sprint 3: organization

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#233]
Dear colleagues 

In one week we’ll start our Sprint3 at CERN. Lars will send you the form to sign in to CERN security in the coming days, and announce where we will meet.

For further information, please check  https://github.com/plazi/arcadia-project/blob/master/sprint%203%2020231029.md

We will start at 10am. Please plan to be ready at this time, that is arrive after 9 am and make sure that all connections, Internet is fully functional at this time.

To start, everybody should prepare a few slides explaining the task you are involved, what your plans have been and still are, what you accomplished, issues,  next steps and whether you would like to work on this topic during the sprint and with whom.  Please keep to a couple of minutes. We dive into details later, so be ready for this too.

For topics you want to work on, please use https://github.com/plazi/arcadia-project/issues/228#issuecomment-1733342534

Looking forwards to meeting you all soon

Donat

**Comment by punkish** [comment]
coffee?☕️

we already have a Plazi coffee machine (probably stashed in Alex's office). Who is bringing the pods and the cups, and a jug to refill the machine?

**Comment by myrmoteras** [comment]
@slint @lars

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by punkish** [comment]
## synchronizing/finalizing agenda

[Google Docs](https://docs.google.com/document/d/1jbo3-RyLwBnssxriZrlMOGwvCsd5CCJbINmXuo6UBrw/edit#heading=h.eg5ed0c8tmw0) says the group dinner is at *Bois Joly* on Wed, 1 November, 2023, while the [Github document](https://github.com/plazi/arcadia-project/blob/master/sprint%203%2020231029.md) says the dinner is at *Carouge* on 2 November, 2023. Which is correct?

@myrmoteras

**Comment by slint** [comment]
> coffee?☕️
> 
> we already have a Plazi coffee machine (probably stashed in Alex's office). Who is bringing the pods and the cups, and a jug to refill the machine?

Besides the Nespresso coffee machine, there's also the Zenodo office coffee machine with free coffee for the first day(s). It's still one flight of stairs from the meeting room, so far from the ideal intravenous coffee delivery we dream of, but it will give us some time to organise.
