### ISSUE TITLE
sprint 4- hotel booking

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#243]
@punkish @Jo-Jo0 @CNaseband @gsautter @tcatapano @flsimoes @peter-cornwell @peterc@blipcreative.com @Thomas61Gehrig @stgrub @dfdan

Dear colleagues 

please confirm what that you will and what the dates are of your participation at the Sprint 4 in CERN, March 10 - 15, and whether you plan to depart on Friday (15) or Saturday (16)

thanks for a reply asap

donat

**Comment by flsimoes** [comment]
I'm leaving on Saturday (16)

Participating the whole week

**Comment by stgrub** [comment]
Tricky week for me: 
If it is anyhow compatible with your planning, I could arrive on Tuesday evening (March 12) and spend Wednesday together with you (March, 13).

I will have to travel back Wednesday evening.

**Comment by Jo-Jo0** [comment]
@gsautter @CNaseband and I will arrive on Sun 10 afternoon/evening and stay until Friday 15.
