### ISSUE TITLE
Two new Pensoft XML biodiversity journals to add to Plazi's harvester

### ISSUE THREAD

**Issue by lyubomirpenev** [plazi/arcadia-project#48]
- [ ] Herpetozoa - https://herpetozoa.pensoft.net/ 
Web services: https://herpetozoa.pensoft.net/about#Webservices

- [ ] Neotropical Biology and Conservation - https://neotropical.pensoft.net/
Web services: https://neotropical.pensoft.net/about#Webservices

**Comment by gsautter** [comment]
Added. Came out with a good few articles already.
