### ISSUE TITLE
treatment upload to Zenodo: tables in descripion field

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#66]
> Getting there ... tables don't seem to work, though: https://sandbox.zenodo.org/record/317260
Should I filter tables altogether in the description? see https://github.com/plazi/arcadia-project/issues/62

@lnielsen @ale why don't work tables in the description field? Is there a way to display them?

**Comment by tcatapano** [comment]
closing in favor of already open issue #65
