### ISSUE TITLE
geodata in treatment deposition metadata

### ISSUE THREAD

**Issue by tcatapano** [plazi/arcadia-project#67]
from: https://github.com/plazi/arcadia-project/issues/62#issuecomment-513474896

@gsautter: see the info on geodata metadata 
at

:https://codimd.web.cern.ch/k2hhtG5cR_qLncq14ouVgA#Geographical

hope this helps

**Comment by gsautter** [comment]
Thanks ... `locations` is not in the documentation yet ... see (or rather don't) http://developers.zenodo.org

**Comment by tcatapano** [comment]
closing in favor of #68
