### ISSUE TITLE
geographic data in deposition uploads

### ISSUE THREAD

**Issue by tcatapano** [plazi/arcadia-project#68]
> For the geographic data, I have to figure out what fields to put it in. http://developers.zenodo.org/ doesn't say anything in this regard ... @lnielsen could you help me out here? Just need to know what JSON to generate ...

_Originally posted by @gsautter in https://github.com/plazi/arcadia-project/issues/62#issuecomment-513474896_

see: https://codimd.web.cern.ch/k2hhtG5cR_qLncq14ouVgA#Geographical

**Comment by gsautter** [comment]
@lnielsen is `locations` a valid field in deposition metadata at this point? http://developers.zenodo.org/ doesn't say anything in this regard ...

**Comment by gsautter** [comment]
Got it, it's only listed in the Sandbox documentation for now.
