### ISSUE TITLE
Access to CERN for Arcadia sprint 20190909

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#79]
@lnielsen 
here are three more that need access to CERN for our next sprint

Lyubo Penev <lyubo.penev@gmail.com>
Willi Egloff <egloff_bader@bluewin.ch>
Reto Gmür <reto@factsmission.com>

see also https://github.com/plazi/arcadia-project/issues/28#issuecomment-469577743

**Comment by lnielsen** [comment]
Done
