### ISSUE TITLE
dataCite type specification

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#86]
@slint @lnielsen 

the dataCite metadata for this treatment deposit in the sandbox

https://sandbox.zenodo.org/record/367955#.XYHdJygzbAQ

 does not include a value for the resourceType element:

`<resourceType resourceTypeGeneral="Text"/>`

https://sandbox.zenodo.org/record/367955/export/dcite4

 however, an article deposit's metadata does have the value of "Journal article" 

`<resourceType resourceTypeGeneral="Text">Journal article</resourceType>`

we would like the taxon treatment dataCite metadata have the value "section" for the value of resourceType, or ideally "taxon treatment". Is this possible?

**Comment by slint** [comment]
Just checked, we forgot to add the DataCite-specific description. Today we'll deploy most of the UI fixes, including this one. I'll close this issue after the Sandbox deployment

**Comment by slint** [comment]
The type is correctly serialized now:

`<resourceType resourceTypeGeneral="Text">Taxonomic treatment</resourceType>`
