### ISSUE TITLE
application/vnd.taxpub.v1+xml

### ISSUE THREAD

**Issue by teodorgeorgiev** [plazi/arcadia-project#93]
Hi Alex, can you please add similary to "application/vnd.plazi.v1+xml" which is displayed as "Plazi XML" a new Content-Type:
- "Content-Type": "application/vnd.taxpub.v1+xml"  
We would like to submit our XMLs with this new content-type and they to be displayed at Zenodo as "TaxPub XML" in the list ot suppl. files.

**Comment by slint** [comment]
Added and available in both Sandbox and Production
