### ISSUE TITLE
license for treatments: which one?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/arcadia-project#96]
@advocomplex which license shall we use for the treatments? CC 0?

![image](https://user-images.githubusercontent.com/4609956/65420479-8e956600-de01-11e9-83f4-2bce52f53d21.png)

https://sandbox.zenodo.org/record/367955#.XYhu5igzbAQ

**Comment by gsautter** [comment]
I was going to go with "License not applicable", in accordance with our policy of years ... unless the article proper has an open license, of course, in which case we should most likely reuse that.

**Comment by advocomplex** [comment]
Yes, CC0!

Von meinem iPad gesendet

**Comment by gsautter** [comment]
Always CC0? Even if the source article is CC-BY?

**Comment by myrmoteras** [comment]
CC 0
Taxonomic treatments are not copyrightable
Taxonomic treatments and descriptions of species are not copyrightable because they lack creativity of form. Rather, they are presented with a standardized form of expression for better comprehension.
http://www.biomedcentral.com/1756-0500/7/79

**Comment by gsautter** [comment]
OK, then I'll hard-wire CC0 for now.
